# """Initial migration

# Revision ID: 3e21c478e88e
# Revises: 845bbbc4d048
# Create Date: 2024-12-12 19:31:15.551420

# """
# from typing import Sequence, Union

# from alembic import op
# import sqlalchemy as sa


# # revision identifiers, used by Alembic.
# revision: str = '3e21c478e88e'
# down_revision: Union[str, None] = '845bbbc4d048'
# branch_labels: Union[str, Sequence[str], None] = None
# depends_on: Union[str, Sequence[str], None] = None


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     pass
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     pass
#     # ### end Alembic commands ###




#修正版
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import TIMESTAMP


# revision identifiers, used by Alembic.
revision = '3e21c478e88e'
down_revision = '845bbbc4d048'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # テーブルを作成
    op.create_table(
        'ideas',
        sa.Column('id', sa.Integer, primary_key=True, autoincrement=True),
        sa.Column('created_at', TIMESTAMP(timezone=True), nullable=False),
        sa.Column('title', sa.Text, nullable=False),
        sa.Column('content', sa.Text, nullable=False),
        sa.Column('tags', sa.Text, nullable=True),
    )


def downgrade() -> None:
    # テーブルを削除
    op.drop_table('ideas')
